-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Loop_1_proc10 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Atile_V_vec_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    Atile_V_vec_0_empty_n : IN STD_LOGIC;
    Atile_V_vec_0_read : OUT STD_LOGIC;
    Atile_V_vec_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    Atile_V_vec_1_empty_n : IN STD_LOGIC;
    Atile_V_vec_1_read : OUT STD_LOGIC;
    A_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_full_n : IN STD_LOGIC;
    A_write : OUT STD_LOGIC );
end;


architecture behav of Loop_1_proc10 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal Atile_V_vec_0_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln8_fu_81_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Atile_V_vec_1_blk_n : STD_LOGIC;
    signal A_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln10_reg_142 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_0_i_i_i_reg_70 : STD_LOGIC_VECTOR (1 downto 0);
    signal io_acc_block_signal_op15 : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal i_fu_87_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_reg_127 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_vec_0_reg_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_vec_1_reg_137 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln10_fu_101_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal j_fu_107_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal trunc_ln11_fu_113_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln11_reg_151 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal i_0_i_i_i_reg_59 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_0_i_i_i_reg_59_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                i_0_i_i_i_reg_59 <= i_reg_127;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_i_i_i_reg_59 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    j_0_i_i_i_reg_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln10_fu_101_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_0_i_i_i_reg_70 <= j_fu_107_p2;
            elsif ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_i_i_i_reg_70 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                i_reg_127 <= i_fu_87_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln10_reg_142 <= icmp_ln10_fu_101_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_vec_0_reg_132 <= Atile_V_vec_0_dout;
                tmp_vec_1_reg_137 <= Atile_V_vec_1_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln10_fu_101_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln11_reg_151 <= trunc_ln11_fu_113_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln8_fu_81_p2, io_acc_block_signal_op15, icmp_ln10_fu_101_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((icmp_ln10_fu_101_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((icmp_ln10_fu_101_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    A_blk_n_assign_proc : process(A_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln10_reg_142)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln10_reg_142 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_blk_n <= A_full_n;
        else 
            A_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    A_din <= 
        tmp_vec_1_reg_137 when (trunc_ln11_reg_151(0) = '1') else 
        tmp_vec_0_reg_132;

    A_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln10_reg_142, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln10_reg_142 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_write <= ap_const_logic_1;
        else 
            A_write <= ap_const_logic_0;
        end if; 
    end process;


    Atile_V_vec_0_blk_n_assign_proc : process(Atile_V_vec_0_empty_n, ap_CS_fsm_state2, icmp_ln8_fu_81_p2)
    begin
        if (((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            Atile_V_vec_0_blk_n <= Atile_V_vec_0_empty_n;
        else 
            Atile_V_vec_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Atile_V_vec_0_read_assign_proc : process(ap_CS_fsm_state2, icmp_ln8_fu_81_p2, io_acc_block_signal_op15)
    begin
        if ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            Atile_V_vec_0_read <= ap_const_logic_1;
        else 
            Atile_V_vec_0_read <= ap_const_logic_0;
        end if; 
    end process;


    Atile_V_vec_1_blk_n_assign_proc : process(Atile_V_vec_1_empty_n, ap_CS_fsm_state2, icmp_ln8_fu_81_p2)
    begin
        if (((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            Atile_V_vec_1_blk_n <= Atile_V_vec_1_empty_n;
        else 
            Atile_V_vec_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Atile_V_vec_1_read_assign_proc : process(ap_CS_fsm_state2, icmp_ln8_fu_81_p2, io_acc_block_signal_op15)
    begin
        if ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            Atile_V_vec_1_read <= ap_const_logic_1;
        else 
            Atile_V_vec_1_read <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(A_full_n, ap_enable_reg_pp0_iter1, icmp_ln10_reg_142)
    begin
                ap_block_pp0_stage0_01001 <= ((icmp_ln10_reg_142 = ap_const_lv1_0) and (ap_const_logic_0 = A_full_n) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(A_full_n, ap_enable_reg_pp0_iter1, icmp_ln10_reg_142)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln10_reg_142 = ap_const_lv1_0) and (ap_const_logic_0 = A_full_n) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(A_full_n, ap_enable_reg_pp0_iter1, icmp_ln10_reg_142)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln10_reg_142 = ap_const_lv1_0) and (ap_const_logic_0 = A_full_n) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(icmp_ln8_fu_81_p2, io_acc_block_signal_op15)
    begin
                ap_block_state2 <= ((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(A_full_n, icmp_ln10_reg_142)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((icmp_ln10_reg_142 = ap_const_lv1_0) and (ap_const_logic_0 = A_full_n));
    end process;


    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln10_fu_101_p2)
    begin
        if ((icmp_ln10_fu_101_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln8_fu_81_p2, io_acc_block_signal_op15)
    begin
        if ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln8_fu_81_p2, io_acc_block_signal_op15)
    begin
        if ((not(((icmp_ln8_fu_81_p2 = ap_const_lv1_0) and (io_acc_block_signal_op15 = ap_const_logic_0))) and (icmp_ln8_fu_81_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_87_p2 <= std_logic_vector(unsigned(i_0_i_i_i_reg_59) + unsigned(ap_const_lv2_1));
    icmp_ln10_fu_101_p2 <= "1" when (j_0_i_i_i_reg_70 = ap_const_lv2_2) else "0";
    icmp_ln8_fu_81_p2 <= "1" when (i_0_i_i_i_reg_59 = ap_const_lv2_2) else "0";
    io_acc_block_signal_op15 <= (Atile_V_vec_1_empty_n and Atile_V_vec_0_empty_n);
    j_fu_107_p2 <= std_logic_vector(unsigned(j_0_i_i_i_reg_70) + unsigned(ap_const_lv2_1));
    trunc_ln11_fu_113_p1 <= j_0_i_i_i_reg_70(1 - 1 downto 0);
end behav;
