// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Loop_memset_y_proc_HH_
#define _Loop_memset_y_proc_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Loop_memset_y_proc : public sc_module {
    // Port declarations 18
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<1> > y_address0;
    sc_out< sc_logic > y_ce0;
    sc_out< sc_logic > y_we0;
    sc_out< sc_lv<32> > y_d0;
    sc_in< sc_lv<32> > y_q0;
    sc_in< sc_lv<32> > A_dout;
    sc_in< sc_logic > A_empty_n;
    sc_out< sc_logic > A_read;
    sc_out< sc_lv<1> > x_address0;
    sc_out< sc_logic > x_ce0;
    sc_in< sc_lv<32> > x_q0;


    // Module declarations
    Loop_memset_y_proc(sc_module_name name);
    SC_HAS_PROCESS(Loop_memset_y_proc);

    ~Loop_memset_y_proc();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > A_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage1;
    sc_signal< sc_lv<1> > icmp_ln26_reg_226;
    sc_signal< sc_lv<3> > indvar_flatten_reg_113;
    sc_signal< sc_lv<2> > i4_0_i_reg_124;
    sc_signal< sc_lv<2> > j5_0_i_reg_135;
    sc_signal< sc_lv<1> > xor_ln25_fu_151_p2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln26_fu_157_p2;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<1> > icmp_ln26_reg_226_pp0_iter1_reg;
    sc_signal< sc_lv<3> > add_ln26_fu_163_p2;
    sc_signal< sc_lv<3> > add_ln26_reg_230;
    sc_signal< sc_lv<2> > select_ln28_fu_175_p3;
    sc_signal< sc_lv<2> > select_ln28_reg_235;
    sc_signal< sc_lv<2> > select_ln28_1_fu_189_p3;
    sc_signal< sc_lv<2> > select_ln28_1_reg_240;
    sc_signal< sc_lv<32> > A_read_reg_251;
    sc_signal< bool > ap_block_state4_pp0_stage1_iter0;
    sc_signal< bool > ap_block_state6_pp0_stage1_iter1;
    sc_signal< bool > ap_block_pp0_stage1_11001;
    sc_signal< sc_lv<32> > x_load_reg_256;
    sc_signal< sc_lv<2> > j_fu_202_p2;
    sc_signal< sc_lv<2> > j_reg_261;
    sc_signal< sc_lv<32> > mul_ln28_fu_211_p2;
    sc_signal< sc_lv<32> > mul_ln28_reg_266;
    sc_signal< sc_lv<1> > y_addr_1_reg_271;
    sc_signal< sc_lv<1> > ap_phi_mux_phi_ln25_i_phi_fu_105_p4;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage1_subdone;
    sc_signal< sc_lv<1> > phi_ln25_i_reg_101;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<3> > ap_phi_mux_indvar_flatten_phi_fu_117_p4;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<2> > ap_phi_mux_i4_0_i_phi_fu_128_p4;
    sc_signal< sc_lv<2> > ap_phi_mux_j5_0_i_phi_fu_139_p4;
    sc_signal< sc_lv<64> > zext_ln25_fu_146_p1;
    sc_signal< sc_lv<64> > zext_ln28_1_fu_197_p1;
    sc_signal< sc_lv<64> > zext_ln28_fu_207_p1;
    sc_signal< sc_lv<32> > add_ln28_fu_215_p2;
    sc_signal< sc_lv<1> > icmp_ln27_fu_169_p2;
    sc_signal< sc_lv<2> > add_ln26_1_fu_183_p2;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_pp0_stage0;
    static const sc_lv<5> ap_ST_fsm_pp0_stage1;
    static const sc_lv<5> ap_ST_fsm_state7;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_4;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_A_blk_n();
    void thread_A_read();
    void thread_add_ln26_1_fu_183_p2();
    void thread_add_ln26_fu_163_p2();
    void thread_add_ln28_fu_215_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state7();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_pp0_stage1();
    void thread_ap_block_pp0_stage1_11001();
    void thread_ap_block_pp0_stage1_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state3_pp0_stage0_iter0();
    void thread_ap_block_state4_pp0_stage1_iter0();
    void thread_ap_block_state5_pp0_stage0_iter1();
    void thread_ap_block_state6_pp0_stage1_iter1();
    void thread_ap_condition_pp0_exit_iter0_state3();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_i4_0_i_phi_fu_128_p4();
    void thread_ap_phi_mux_indvar_flatten_phi_fu_117_p4();
    void thread_ap_phi_mux_j5_0_i_phi_fu_139_p4();
    void thread_ap_phi_mux_phi_ln25_i_phi_fu_105_p4();
    void thread_ap_ready();
    void thread_icmp_ln26_fu_157_p2();
    void thread_icmp_ln27_fu_169_p2();
    void thread_j_fu_202_p2();
    void thread_mul_ln28_fu_211_p2();
    void thread_select_ln28_1_fu_189_p3();
    void thread_select_ln28_fu_175_p3();
    void thread_x_address0();
    void thread_x_ce0();
    void thread_xor_ln25_fu_151_p2();
    void thread_y_address0();
    void thread_y_ce0();
    void thread_y_d0();
    void thread_y_we0();
    void thread_zext_ln25_fu_146_p1();
    void thread_zext_ln28_1_fu_197_p1();
    void thread_zext_ln28_fu_207_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
