// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "tiled_matvec.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic tiled_matvec::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic tiled_matvec::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> tiled_matvec::ap_ST_fsm_state1 = "1";
const sc_lv<9> tiled_matvec::ap_ST_fsm_state2 = "10";
const sc_lv<9> tiled_matvec::ap_ST_fsm_state3 = "100";
const sc_lv<9> tiled_matvec::ap_ST_fsm_state4 = "1000";
const sc_lv<9> tiled_matvec::ap_ST_fsm_state5 = "10000";
const sc_lv<9> tiled_matvec::ap_ST_fsm_state6 = "100000";
const sc_lv<9> tiled_matvec::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> tiled_matvec::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> tiled_matvec::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> tiled_matvec::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool tiled_matvec::ap_const_boolean_1 = true;
const sc_lv<32> tiled_matvec::ap_const_lv32_1 = "1";
const sc_lv<1> tiled_matvec::ap_const_lv1_0 = "0";
const sc_lv<1> tiled_matvec::ap_const_lv1_1 = "1";
const sc_lv<32> tiled_matvec::ap_const_lv32_2 = "10";
const sc_lv<32> tiled_matvec::ap_const_lv32_3 = "11";
const sc_lv<32> tiled_matvec::ap_const_lv32_4 = "100";
const sc_lv<32> tiled_matvec::ap_const_lv32_5 = "101";
const sc_lv<32> tiled_matvec::ap_const_lv32_7 = "111";
const sc_lv<2> tiled_matvec::ap_const_lv2_0 = "00";
const sc_lv<32> tiled_matvec::ap_const_lv32_6 = "110";
const sc_lv<32> tiled_matvec::ap_const_lv32_8 = "1000";
const sc_lv<2> tiled_matvec::ap_const_lv2_2 = "10";
const sc_lv<2> tiled_matvec::ap_const_lv2_1 = "1";

tiled_matvec::tiled_matvec(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Atile_V_vec_0_blk_n);
    sensitive << ( Atile_V_vec_0_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );

    SC_METHOD(thread_Atile_V_vec_0_read);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op36 );
    sensitive << ( ap_predicate_op36_read_state2 );

    SC_METHOD(thread_Atile_V_vec_1_blk_n);
    sensitive << ( Atile_V_vec_1_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );

    SC_METHOD(thread_Atile_V_vec_1_read);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op36 );
    sensitive << ( ap_predicate_op36_read_state2 );

    SC_METHOD(thread_add_ln35_fu_502_p2);
    sensitive << ( shl_ln35_reg_654 );
    sensitive << ( zext_ln33_fu_486_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op36 );
    sensitive << ( ap_predicate_op36_read_state2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln33_fu_490_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_predicate_op36_read_state2);
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( icmp_ln17_fu_254_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln33_fu_490_p2 );

    SC_METHOD(thread_i_1_fu_388_p2);
    sensitive << ( i4_0_reg_190 );

    SC_METHOD(thread_i_3_fu_320_p2);
    sensitive << ( i3_0_reg_179 );

    SC_METHOD(thread_i_4_fu_496_p2);
    sensitive << ( i6_0_reg_212 );

    SC_METHOD(thread_i_fu_236_p2);
    sensitive << ( i_0_reg_157 );

    SC_METHOD(thread_icmp_ln10_fu_268_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_0_reg_168 );

    SC_METHOD(thread_icmp_ln17_fu_254_p2);
    sensitive << ( i2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op36 );
    sensitive << ( ap_predicate_op36_read_state2 );

    SC_METHOD(thread_icmp_ln19_fu_314_p2);
    sensitive << ( icmp_ln17_reg_558 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i3_0_reg_179 );

    SC_METHOD(thread_icmp_ln26_fu_382_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i4_0_reg_190 );

    SC_METHOD(thread_icmp_ln27_fu_403_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j5_0_reg_201 );

    SC_METHOD(thread_icmp_ln33_fu_490_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( i6_0_reg_212 );

    SC_METHOD(thread_icmp_ln8_fu_230_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op36 );
    sensitive << ( ap_predicate_op36_read_state2 );
    sensitive << ( i_0_reg_157 );

    SC_METHOD(thread_io_acc_block_signal_op28);
    sensitive << ( Atile_V_vec_0_empty_n );
    sensitive << ( Atile_V_vec_1_empty_n );

    SC_METHOD(thread_io_acc_block_signal_op36);
    sensitive << ( xtile_V_vec_0_empty_n );
    sensitive << ( xtile_V_vec_1_empty_n );

    SC_METHOD(thread_j_1_fu_409_p2);
    sensitive << ( j5_0_reg_201 );

    SC_METHOD(thread_j_fu_274_p2);
    sensitive << ( j_0_reg_168 );

    SC_METHOD(thread_mul_ln28_fu_444_p2);
    sensitive << ( select_ln28_4_fu_431_p3 );
    sensitive << ( select_ln28_2_fu_438_p3 );

    SC_METHOD(thread_select_ln11_fu_284_p3);
    sensitive << ( tmp_vec_0_reg_539 );
    sensitive << ( tmp_vec_1_reg_544 );
    sensitive << ( trunc_ln11_1_fu_280_p1 );

    SC_METHOD(thread_select_ln20_fu_330_p3);
    sensitive << ( tmp_vec_0_1_reg_562 );
    sensitive << ( tmp_vec_1_1_reg_567 );
    sensitive << ( trunc_ln20_fu_326_p1 );

    SC_METHOD(thread_select_ln28_1_fu_419_p3);
    sensitive << ( A_1_0_load_reg_608 );
    sensitive << ( A_1_1_load_reg_613 );
    sensitive << ( trunc_ln28_1_fu_415_p1 );

    SC_METHOD(thread_select_ln28_2_fu_438_p3);
    sensitive << ( x_0_load_reg_618 );
    sensitive << ( x_1_load_reg_623 );
    sensitive << ( trunc_ln28_1_fu_415_p1 );

    SC_METHOD(thread_select_ln28_3_fu_450_p3);
    sensitive << ( trunc_ln28_reg_646 );
    sensitive << ( y_1_fu_114 );
    sensitive << ( y_1_3_fu_118 );

    SC_METHOD(thread_select_ln28_4_fu_431_p3);
    sensitive << ( trunc_ln28_reg_646 );
    sensitive << ( select_ln28_1_fu_419_p3 );
    sensitive << ( select_ln28_fu_425_p3 );

    SC_METHOD(thread_select_ln28_fu_425_p3);
    sensitive << ( A_0_0_load_reg_628 );
    sensitive << ( A_0_1_load_reg_633 );
    sensitive << ( trunc_ln28_1_fu_415_p1 );

    SC_METHOD(thread_select_ln35_fu_516_p3);
    sensitive << ( y_1_fu_114 );
    sensitive << ( y_1_3_fu_118 );
    sensitive << ( trunc_ln35_fu_512_p1 );

    SC_METHOD(thread_sext_ln35_fu_507_p1);
    sensitive << ( add_ln35_fu_502_p2 );

    SC_METHOD(thread_shl_ln35_fu_398_p2);
    sensitive << ( i2 );

    SC_METHOD(thread_trunc_ln11_1_fu_280_p1);
    sensitive << ( j_0_reg_168 );

    SC_METHOD(thread_trunc_ln11_fu_250_p1);
    sensitive << ( i_0_reg_157 );

    SC_METHOD(thread_trunc_ln20_fu_326_p1);
    sensitive << ( i3_0_reg_179 );

    SC_METHOD(thread_trunc_ln28_1_fu_415_p1);
    sensitive << ( j5_0_reg_201 );

    SC_METHOD(thread_trunc_ln28_fu_394_p1);
    sensitive << ( i4_0_reg_190 );

    SC_METHOD(thread_trunc_ln35_fu_512_p1);
    sensitive << ( i6_0_reg_212 );

    SC_METHOD(thread_xtile_V_vec_0_blk_n);
    sensitive << ( xtile_V_vec_0_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( icmp_ln17_fu_254_p2 );

    SC_METHOD(thread_xtile_V_vec_0_read);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op36 );
    sensitive << ( ap_predicate_op36_read_state2 );

    SC_METHOD(thread_xtile_V_vec_1_blk_n);
    sensitive << ( xtile_V_vec_1_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( icmp_ln17_fu_254_p2 );

    SC_METHOD(thread_xtile_V_vec_1_read);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op36 );
    sensitive << ( ap_predicate_op36_read_state2 );

    SC_METHOD(thread_y_0_fu_457_p2);
    sensitive << ( mul_ln28_reg_667 );
    sensitive << ( select_ln28_3_fu_450_p3 );

    SC_METHOD(thread_y_1_5_fu_462_p3);
    sensitive << ( trunc_ln28_reg_646 );
    sensitive << ( y_1_3_fu_118 );
    sensitive << ( y_0_fu_457_p2 );

    SC_METHOD(thread_y_1_6_fu_469_p3);
    sensitive << ( trunc_ln28_reg_646 );
    sensitive << ( y_1_fu_114 );
    sensitive << ( y_0_fu_457_p2 );

    SC_METHOD(thread_ypartial_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ypartial_addr_reg_680 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( sext_ln35_fu_507_p1 );

    SC_METHOD(thread_ypartial_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_ypartial_d0);
    sensitive << ( ypartial_q0 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( select_ln35_fu_516_p3 );

    SC_METHOD(thread_ypartial_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_zext_ln33_fu_486_p1);
    sensitive << ( i6_0_reg_212 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_230_p2 );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op36 );
    sensitive << ( ap_predicate_op36_read_state2 );
    sensitive << ( icmp_ln17_reg_558 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln19_fu_314_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln26_fu_382_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln27_fu_403_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln33_fu_490_p2 );
    sensitive << ( icmp_ln10_fu_268_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000001";
    A_1_0 = "00000000000000000000000000000000";
    A_1_1 = "00000000000000000000000000000000";
    x_0 = "00000000000000000000000000000000";
    x_1 = "00000000000000000000000000000000";
    A_0_0 = "00000000000000000000000000000000";
    A_0_1 = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "tiled_matvec_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, Atile_V_vec_0_dout, "(port)Atile_V_vec_0_dout");
    sc_trace(mVcdFile, Atile_V_vec_0_empty_n, "(port)Atile_V_vec_0_empty_n");
    sc_trace(mVcdFile, Atile_V_vec_0_read, "(port)Atile_V_vec_0_read");
    sc_trace(mVcdFile, Atile_V_vec_1_dout, "(port)Atile_V_vec_1_dout");
    sc_trace(mVcdFile, Atile_V_vec_1_empty_n, "(port)Atile_V_vec_1_empty_n");
    sc_trace(mVcdFile, Atile_V_vec_1_read, "(port)Atile_V_vec_1_read");
    sc_trace(mVcdFile, xtile_V_vec_0_dout, "(port)xtile_V_vec_0_dout");
    sc_trace(mVcdFile, xtile_V_vec_0_empty_n, "(port)xtile_V_vec_0_empty_n");
    sc_trace(mVcdFile, xtile_V_vec_0_read, "(port)xtile_V_vec_0_read");
    sc_trace(mVcdFile, xtile_V_vec_1_dout, "(port)xtile_V_vec_1_dout");
    sc_trace(mVcdFile, xtile_V_vec_1_empty_n, "(port)xtile_V_vec_1_empty_n");
    sc_trace(mVcdFile, xtile_V_vec_1_read, "(port)xtile_V_vec_1_read");
    sc_trace(mVcdFile, ypartial_address0, "(port)ypartial_address0");
    sc_trace(mVcdFile, ypartial_ce0, "(port)ypartial_ce0");
    sc_trace(mVcdFile, ypartial_we0, "(port)ypartial_we0");
    sc_trace(mVcdFile, ypartial_d0, "(port)ypartial_d0");
    sc_trace(mVcdFile, ypartial_q0, "(port)ypartial_q0");
    sc_trace(mVcdFile, i1, "(port)i1");
    sc_trace(mVcdFile, i2, "(port)i2");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, A_1_0, "A_1_0");
    sc_trace(mVcdFile, A_1_1, "A_1_1");
    sc_trace(mVcdFile, x_0, "x_0");
    sc_trace(mVcdFile, x_1, "x_1");
    sc_trace(mVcdFile, A_0_0, "A_0_0");
    sc_trace(mVcdFile, A_0_1, "A_0_1");
    sc_trace(mVcdFile, Atile_V_vec_0_blk_n, "Atile_V_vec_0_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln8_fu_230_p2, "icmp_ln8_fu_230_p2");
    sc_trace(mVcdFile, Atile_V_vec_1_blk_n, "Atile_V_vec_1_blk_n");
    sc_trace(mVcdFile, xtile_V_vec_0_blk_n, "xtile_V_vec_0_blk_n");
    sc_trace(mVcdFile, icmp_ln17_fu_254_p2, "icmp_ln17_fu_254_p2");
    sc_trace(mVcdFile, xtile_V_vec_1_blk_n, "xtile_V_vec_1_blk_n");
    sc_trace(mVcdFile, i_fu_236_p2, "i_fu_236_p2");
    sc_trace(mVcdFile, i_reg_534, "i_reg_534");
    sc_trace(mVcdFile, io_acc_block_signal_op28, "io_acc_block_signal_op28");
    sc_trace(mVcdFile, io_acc_block_signal_op36, "io_acc_block_signal_op36");
    sc_trace(mVcdFile, ap_predicate_op36_read_state2, "ap_predicate_op36_read_state2");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, tmp_vec_0_reg_539, "tmp_vec_0_reg_539");
    sc_trace(mVcdFile, tmp_vec_1_reg_544, "tmp_vec_1_reg_544");
    sc_trace(mVcdFile, trunc_ln11_fu_250_p1, "trunc_ln11_fu_250_p1");
    sc_trace(mVcdFile, trunc_ln11_reg_549, "trunc_ln11_reg_549");
    sc_trace(mVcdFile, icmp_ln17_reg_558, "icmp_ln17_reg_558");
    sc_trace(mVcdFile, tmp_vec_0_1_reg_562, "tmp_vec_0_1_reg_562");
    sc_trace(mVcdFile, tmp_vec_1_1_reg_567, "tmp_vec_1_1_reg_567");
    sc_trace(mVcdFile, j_fu_274_p2, "j_fu_274_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_3_fu_320_p2, "i_3_fu_320_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, A_1_0_load_reg_608, "A_1_0_load_reg_608");
    sc_trace(mVcdFile, icmp_ln19_fu_314_p2, "icmp_ln19_fu_314_p2");
    sc_trace(mVcdFile, A_1_1_load_reg_613, "A_1_1_load_reg_613");
    sc_trace(mVcdFile, x_0_load_reg_618, "x_0_load_reg_618");
    sc_trace(mVcdFile, x_1_load_reg_623, "x_1_load_reg_623");
    sc_trace(mVcdFile, A_0_0_load_reg_628, "A_0_0_load_reg_628");
    sc_trace(mVcdFile, A_0_1_load_reg_633, "A_0_1_load_reg_633");
    sc_trace(mVcdFile, i_1_fu_388_p2, "i_1_fu_388_p2");
    sc_trace(mVcdFile, i_1_reg_641, "i_1_reg_641");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, trunc_ln28_fu_394_p1, "trunc_ln28_fu_394_p1");
    sc_trace(mVcdFile, trunc_ln28_reg_646, "trunc_ln28_reg_646");
    sc_trace(mVcdFile, icmp_ln26_fu_382_p2, "icmp_ln26_fu_382_p2");
    sc_trace(mVcdFile, shl_ln35_fu_398_p2, "shl_ln35_fu_398_p2");
    sc_trace(mVcdFile, shl_ln35_reg_654, "shl_ln35_reg_654");
    sc_trace(mVcdFile, j_1_fu_409_p2, "j_1_fu_409_p2");
    sc_trace(mVcdFile, j_1_reg_662, "j_1_reg_662");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, mul_ln28_fu_444_p2, "mul_ln28_fu_444_p2");
    sc_trace(mVcdFile, mul_ln28_reg_667, "mul_ln28_reg_667");
    sc_trace(mVcdFile, icmp_ln27_fu_403_p2, "icmp_ln27_fu_403_p2");
    sc_trace(mVcdFile, i_4_fu_496_p2, "i_4_fu_496_p2");
    sc_trace(mVcdFile, i_4_reg_675, "i_4_reg_675");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ypartial_addr_reg_680, "ypartial_addr_reg_680");
    sc_trace(mVcdFile, icmp_ln33_fu_490_p2, "icmp_ln33_fu_490_p2");
    sc_trace(mVcdFile, i_0_reg_157, "i_0_reg_157");
    sc_trace(mVcdFile, icmp_ln10_fu_268_p2, "icmp_ln10_fu_268_p2");
    sc_trace(mVcdFile, j_0_reg_168, "j_0_reg_168");
    sc_trace(mVcdFile, i3_0_reg_179, "i3_0_reg_179");
    sc_trace(mVcdFile, i4_0_reg_190, "i4_0_reg_190");
    sc_trace(mVcdFile, j5_0_reg_201, "j5_0_reg_201");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i6_0_reg_212, "i6_0_reg_212");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, sext_ln35_fu_507_p1, "sext_ln35_fu_507_p1");
    sc_trace(mVcdFile, select_ln11_fu_284_p3, "select_ln11_fu_284_p3");
    sc_trace(mVcdFile, trunc_ln11_1_fu_280_p1, "trunc_ln11_1_fu_280_p1");
    sc_trace(mVcdFile, select_ln20_fu_330_p3, "select_ln20_fu_330_p3");
    sc_trace(mVcdFile, trunc_ln20_fu_326_p1, "trunc_ln20_fu_326_p1");
    sc_trace(mVcdFile, y_1_fu_114, "y_1_fu_114");
    sc_trace(mVcdFile, y_1_6_fu_469_p3, "y_1_6_fu_469_p3");
    sc_trace(mVcdFile, y_1_3_fu_118, "y_1_3_fu_118");
    sc_trace(mVcdFile, y_1_5_fu_462_p3, "y_1_5_fu_462_p3");
    sc_trace(mVcdFile, trunc_ln28_1_fu_415_p1, "trunc_ln28_1_fu_415_p1");
    sc_trace(mVcdFile, select_ln28_1_fu_419_p3, "select_ln28_1_fu_419_p3");
    sc_trace(mVcdFile, select_ln28_fu_425_p3, "select_ln28_fu_425_p3");
    sc_trace(mVcdFile, select_ln28_4_fu_431_p3, "select_ln28_4_fu_431_p3");
    sc_trace(mVcdFile, select_ln28_2_fu_438_p3, "select_ln28_2_fu_438_p3");
    sc_trace(mVcdFile, select_ln28_3_fu_450_p3, "select_ln28_3_fu_450_p3");
    sc_trace(mVcdFile, y_0_fu_457_p2, "y_0_fu_457_p2");
    sc_trace(mVcdFile, zext_ln33_fu_486_p1, "zext_ln33_fu_486_p1");
    sc_trace(mVcdFile, add_ln35_fu_502_p2, "add_ln35_fu_502_p2");
    sc_trace(mVcdFile, trunc_ln35_fu_512_p1, "trunc_ln35_fu_512_p1");
    sc_trace(mVcdFile, select_ln35_fu_516_p3, "select_ln35_fu_516_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("tiled_matvec.hdltvin.dat");
    mHdltvoutHandle.open("tiled_matvec.hdltvout.dat");
}

tiled_matvec::~tiled_matvec() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void tiled_matvec::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_reg_558.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_314_p2.read()))) {
        i3_0_reg_179 = i_3_fu_320_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_254_p2.read()) && 
                !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
        i3_0_reg_179 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln27_fu_403_p2.read()))) {
        i4_0_reg_190 = i_1_reg_641.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln19_fu_314_p2.read()) || 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_reg_558.read())))) {
        i4_0_reg_190 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln26_fu_382_p2.read()))) {
        i6_0_reg_212 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i6_0_reg_212 = i_4_reg_675.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln10_fu_268_p2.read()))) {
        i_0_reg_157 = i_reg_534.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_157 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j5_0_reg_201 = j_1_reg_662.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln26_fu_382_p2.read()))) {
        j5_0_reg_201 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_268_p2.read()))) {
        j_0_reg_168 = j_fu_274_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
                !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
        j_0_reg_168 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_1_3_fu_118 = y_1_5_fu_462_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln19_fu_314_p2.read()) || 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_reg_558.read())))) {
        y_1_3_fu_118 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_1_fu_114 = y_1_6_fu_469_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln19_fu_314_p2.read()) || 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_reg_558.read())))) {
        y_1_fu_114 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_268_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln11_1_fu_280_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln11_reg_549.read()))) {
        A_0_0 = select_ln11_fu_284_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln19_fu_314_p2.read()) || 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_reg_558.read())))) {
        A_0_0_load_reg_628 = A_0_0.read();
        A_0_1_load_reg_633 = A_0_1.read();
        A_1_0_load_reg_608 = A_1_0.read();
        A_1_1_load_reg_613 = A_1_1.read();
        x_0_load_reg_618 = x_0.read();
        x_1_load_reg_623 = x_1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_268_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln11_1_fu_280_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln11_reg_549.read()))) {
        A_0_1 = select_ln11_fu_284_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_268_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln11_reg_549.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln11_1_fu_280_p1.read()))) {
        A_1_0 = select_ln11_fu_284_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_268_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln11_reg_549.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln11_1_fu_280_p1.read()))) {
        A_1_1 = select_ln11_fu_284_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_1_reg_641 = i_1_fu_388_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_4_reg_675 = i_4_fu_496_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
        i_reg_534 = i_fu_236_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_1) && !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
        icmp_ln17_reg_558 = icmp_ln17_fu_254_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_1_reg_662 = j_1_fu_409_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_fu_403_p2.read()))) {
        mul_ln28_reg_667 = mul_ln28_fu_444_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln26_fu_382_p2.read()))) {
        shl_ln35_reg_654 = shl_ln35_fu_398_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_254_p2.read()) && !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
        tmp_vec_0_1_reg_562 = xtile_V_vec_0_dout.read();
        tmp_vec_1_1_reg_567 = xtile_V_vec_1_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
        tmp_vec_0_reg_539 = Atile_V_vec_0_dout.read();
        tmp_vec_1_reg_544 = Atile_V_vec_1_dout.read();
        trunc_ln11_reg_549 = trunc_ln11_fu_250_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln26_fu_382_p2.read()))) {
        trunc_ln28_reg_646 = trunc_ln28_fu_394_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_reg_558.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_314_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln20_fu_326_p1.read()))) {
        x_0 = select_ln20_fu_330_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_reg_558.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_314_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln20_fu_326_p1.read()))) {
        x_1 = select_ln20_fu_330_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln33_fu_490_p2.read()))) {
        ypartial_addr_reg_680 =  (sc_lv<3>) (sext_ln35_fu_507_p1.read());
    }
}

void tiled_matvec::thread_Atile_V_vec_0_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0))) {
        Atile_V_vec_0_blk_n = Atile_V_vec_0_empty_n.read();
    } else {
        Atile_V_vec_0_blk_n = ap_const_logic_1;
    }
}

void tiled_matvec::thread_Atile_V_vec_0_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
        Atile_V_vec_0_read = ap_const_logic_1;
    } else {
        Atile_V_vec_0_read = ap_const_logic_0;
    }
}

void tiled_matvec::thread_Atile_V_vec_1_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0))) {
        Atile_V_vec_1_blk_n = Atile_V_vec_1_empty_n.read();
    } else {
        Atile_V_vec_1_blk_n = ap_const_logic_1;
    }
}

void tiled_matvec::thread_Atile_V_vec_1_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
        Atile_V_vec_1_read = ap_const_logic_1;
    } else {
        Atile_V_vec_1_read = ap_const_logic_0;
    }
}

void tiled_matvec::thread_add_ln35_fu_502_p2() {
    add_ln35_fu_502_p2 = (!zext_ln33_fu_486_p1.read().is_01() || !shl_ln35_reg_654.read().is_01())? sc_lv<32>(): (sc_biguint<32>(zext_ln33_fu_486_p1.read()) + sc_biguint<32>(shl_ln35_reg_654.read()));
}

void tiled_matvec::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void tiled_matvec::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void tiled_matvec::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void tiled_matvec::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void tiled_matvec::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void tiled_matvec::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void tiled_matvec::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void tiled_matvec::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void tiled_matvec::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void tiled_matvec::thread_ap_block_state2() {
    ap_block_state2 = ((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read())));
}

void tiled_matvec::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln33_fu_490_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void tiled_matvec::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void tiled_matvec::thread_ap_predicate_op36_read_state2() {
    ap_predicate_op36_read_state2 = (esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_254_p2.read()));
}

void tiled_matvec::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln33_fu_490_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void tiled_matvec::thread_i_1_fu_388_p2() {
    i_1_fu_388_p2 = (!i4_0_reg_190.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i4_0_reg_190.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void tiled_matvec::thread_i_3_fu_320_p2() {
    i_3_fu_320_p2 = (!i3_0_reg_179.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i3_0_reg_179.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void tiled_matvec::thread_i_4_fu_496_p2() {
    i_4_fu_496_p2 = (!i6_0_reg_212.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i6_0_reg_212.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void tiled_matvec::thread_i_fu_236_p2() {
    i_fu_236_p2 = (!i_0_reg_157.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_0_reg_157.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void tiled_matvec::thread_icmp_ln10_fu_268_p2() {
    icmp_ln10_fu_268_p2 = (!j_0_reg_168.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_168.read() == ap_const_lv2_2);
}

void tiled_matvec::thread_icmp_ln17_fu_254_p2() {
    icmp_ln17_fu_254_p2 = (!i2.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(i2.read() == ap_const_lv32_0);
}

void tiled_matvec::thread_icmp_ln19_fu_314_p2() {
    icmp_ln19_fu_314_p2 = (!i3_0_reg_179.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_179.read() == ap_const_lv2_2);
}

void tiled_matvec::thread_icmp_ln26_fu_382_p2() {
    icmp_ln26_fu_382_p2 = (!i4_0_reg_190.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i4_0_reg_190.read() == ap_const_lv2_2);
}

void tiled_matvec::thread_icmp_ln27_fu_403_p2() {
    icmp_ln27_fu_403_p2 = (!j5_0_reg_201.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(j5_0_reg_201.read() == ap_const_lv2_2);
}

void tiled_matvec::thread_icmp_ln33_fu_490_p2() {
    icmp_ln33_fu_490_p2 = (!i6_0_reg_212.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i6_0_reg_212.read() == ap_const_lv2_2);
}

void tiled_matvec::thread_icmp_ln8_fu_230_p2() {
    icmp_ln8_fu_230_p2 = (!i_0_reg_157.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_157.read() == ap_const_lv2_2);
}

void tiled_matvec::thread_io_acc_block_signal_op28() {
    io_acc_block_signal_op28 = (Atile_V_vec_0_empty_n.read() & Atile_V_vec_1_empty_n.read());
}

void tiled_matvec::thread_io_acc_block_signal_op36() {
    io_acc_block_signal_op36 = (xtile_V_vec_0_empty_n.read() & xtile_V_vec_1_empty_n.read());
}

void tiled_matvec::thread_j_1_fu_409_p2() {
    j_1_fu_409_p2 = (!j5_0_reg_201.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j5_0_reg_201.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void tiled_matvec::thread_j_fu_274_p2() {
    j_fu_274_p2 = (!j_0_reg_168.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j_0_reg_168.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void tiled_matvec::thread_mul_ln28_fu_444_p2() {
    mul_ln28_fu_444_p2 = (!select_ln28_4_fu_431_p3.read().is_01() || !select_ln28_2_fu_438_p3.read().is_01())? sc_lv<32>(): sc_bigint<32>(select_ln28_4_fu_431_p3.read()) * sc_bigint<32>(select_ln28_2_fu_438_p3.read());
}

void tiled_matvec::thread_select_ln11_fu_284_p3() {
    select_ln11_fu_284_p3 = (!trunc_ln11_1_fu_280_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln11_1_fu_280_p1.read()[0].to_bool())? tmp_vec_1_reg_544.read(): tmp_vec_0_reg_539.read());
}

void tiled_matvec::thread_select_ln20_fu_330_p3() {
    select_ln20_fu_330_p3 = (!trunc_ln20_fu_326_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln20_fu_326_p1.read()[0].to_bool())? tmp_vec_1_1_reg_567.read(): tmp_vec_0_1_reg_562.read());
}

void tiled_matvec::thread_select_ln28_1_fu_419_p3() {
    select_ln28_1_fu_419_p3 = (!trunc_ln28_1_fu_415_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln28_1_fu_415_p1.read()[0].to_bool())? A_1_1_load_reg_613.read(): A_1_0_load_reg_608.read());
}

void tiled_matvec::thread_select_ln28_2_fu_438_p3() {
    select_ln28_2_fu_438_p3 = (!trunc_ln28_1_fu_415_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln28_1_fu_415_p1.read()[0].to_bool())? x_1_load_reg_623.read(): x_0_load_reg_618.read());
}

void tiled_matvec::thread_select_ln28_3_fu_450_p3() {
    select_ln28_3_fu_450_p3 = (!trunc_ln28_reg_646.read()[0].is_01())? sc_lv<32>(): ((trunc_ln28_reg_646.read()[0].to_bool())? y_1_3_fu_118.read(): y_1_fu_114.read());
}

void tiled_matvec::thread_select_ln28_4_fu_431_p3() {
    select_ln28_4_fu_431_p3 = (!trunc_ln28_reg_646.read()[0].is_01())? sc_lv<32>(): ((trunc_ln28_reg_646.read()[0].to_bool())? select_ln28_1_fu_419_p3.read(): select_ln28_fu_425_p3.read());
}

void tiled_matvec::thread_select_ln28_fu_425_p3() {
    select_ln28_fu_425_p3 = (!trunc_ln28_1_fu_415_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln28_1_fu_415_p1.read()[0].to_bool())? A_0_1_load_reg_633.read(): A_0_0_load_reg_628.read());
}

void tiled_matvec::thread_select_ln35_fu_516_p3() {
    select_ln35_fu_516_p3 = (!trunc_ln35_fu_512_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln35_fu_512_p1.read()[0].to_bool())? y_1_3_fu_118.read(): y_1_fu_114.read());
}

void tiled_matvec::thread_sext_ln35_fu_507_p1() {
    sext_ln35_fu_507_p1 = esl_sext<64,32>(add_ln35_fu_502_p2.read());
}

void tiled_matvec::thread_shl_ln35_fu_398_p2() {
    shl_ln35_fu_398_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): i2.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void tiled_matvec::thread_trunc_ln11_1_fu_280_p1() {
    trunc_ln11_1_fu_280_p1 = j_0_reg_168.read().range(1-1, 0);
}

void tiled_matvec::thread_trunc_ln11_fu_250_p1() {
    trunc_ln11_fu_250_p1 = i_0_reg_157.read().range(1-1, 0);
}

void tiled_matvec::thread_trunc_ln20_fu_326_p1() {
    trunc_ln20_fu_326_p1 = i3_0_reg_179.read().range(1-1, 0);
}

void tiled_matvec::thread_trunc_ln28_1_fu_415_p1() {
    trunc_ln28_1_fu_415_p1 = j5_0_reg_201.read().range(1-1, 0);
}

void tiled_matvec::thread_trunc_ln28_fu_394_p1() {
    trunc_ln28_fu_394_p1 = i4_0_reg_190.read().range(1-1, 0);
}

void tiled_matvec::thread_trunc_ln35_fu_512_p1() {
    trunc_ln35_fu_512_p1 = i6_0_reg_212.read().range(1-1, 0);
}

void tiled_matvec::thread_xtile_V_vec_0_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_254_p2.read()))) {
        xtile_V_vec_0_blk_n = xtile_V_vec_0_empty_n.read();
    } else {
        xtile_V_vec_0_blk_n = ap_const_logic_1;
    }
}

void tiled_matvec::thread_xtile_V_vec_0_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()) && 
         !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
        xtile_V_vec_0_read = ap_const_logic_1;
    } else {
        xtile_V_vec_0_read = ap_const_logic_0;
    }
}

void tiled_matvec::thread_xtile_V_vec_1_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_254_p2.read()))) {
        xtile_V_vec_1_blk_n = xtile_V_vec_1_empty_n.read();
    } else {
        xtile_V_vec_1_blk_n = ap_const_logic_1;
    }
}

void tiled_matvec::thread_xtile_V_vec_1_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()) && 
         !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
        xtile_V_vec_1_read = ap_const_logic_1;
    } else {
        xtile_V_vec_1_read = ap_const_logic_0;
    }
}

void tiled_matvec::thread_y_0_fu_457_p2() {
    y_0_fu_457_p2 = (!mul_ln28_reg_667.read().is_01() || !select_ln28_3_fu_450_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln28_reg_667.read()) + sc_biguint<32>(select_ln28_3_fu_450_p3.read()));
}

void tiled_matvec::thread_y_1_5_fu_462_p3() {
    y_1_5_fu_462_p3 = (!trunc_ln28_reg_646.read()[0].is_01())? sc_lv<32>(): ((trunc_ln28_reg_646.read()[0].to_bool())? y_0_fu_457_p2.read(): y_1_3_fu_118.read());
}

void tiled_matvec::thread_y_1_6_fu_469_p3() {
    y_1_6_fu_469_p3 = (!trunc_ln28_reg_646.read()[0].is_01())? sc_lv<32>(): ((trunc_ln28_reg_646.read()[0].to_bool())? y_1_fu_114.read(): y_0_fu_457_p2.read());
}

void tiled_matvec::thread_ypartial_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ypartial_address0 = ypartial_addr_reg_680.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ypartial_address0 =  (sc_lv<3>) (sext_ln35_fu_507_p1.read());
    } else {
        ypartial_address0 = "XXX";
    }
}

void tiled_matvec::thread_ypartial_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        ypartial_ce0 = ap_const_logic_1;
    } else {
        ypartial_ce0 = ap_const_logic_0;
    }
}

void tiled_matvec::thread_ypartial_d0() {
    ypartial_d0 = (!ypartial_q0.read().is_01() || !select_ln35_fu_516_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ypartial_q0.read()) + sc_biguint<32>(select_ln35_fu_516_p3.read()));
}

void tiled_matvec::thread_ypartial_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ypartial_we0 = ap_const_logic_1;
    } else {
        ypartial_we0 = ap_const_logic_0;
    }
}

void tiled_matvec::thread_zext_ln33_fu_486_p1() {
    zext_ln33_fu_486_p1 = esl_zext<32,2>(i6_0_reg_212.read());
}

void tiled_matvec::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_1) && !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(icmp_ln8_fu_230_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op36.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op36_read_state2.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln10_fu_268_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln19_fu_314_p2.read()) || 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_reg_558.read())))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln26_fu_382_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln27_fu_403_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln33_fu_490_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

void tiled_matvec::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Atile_V_vec_0_dout\" :  \"" << Atile_V_vec_0_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Atile_V_vec_0_empty_n\" :  \"" << Atile_V_vec_0_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Atile_V_vec_0_read\" :  \"" << Atile_V_vec_0_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Atile_V_vec_1_dout\" :  \"" << Atile_V_vec_1_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Atile_V_vec_1_empty_n\" :  \"" << Atile_V_vec_1_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Atile_V_vec_1_read\" :  \"" << Atile_V_vec_1_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"xtile_V_vec_0_dout\" :  \"" << xtile_V_vec_0_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"xtile_V_vec_0_empty_n\" :  \"" << xtile_V_vec_0_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"xtile_V_vec_0_read\" :  \"" << xtile_V_vec_0_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"xtile_V_vec_1_dout\" :  \"" << xtile_V_vec_1_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"xtile_V_vec_1_empty_n\" :  \"" << xtile_V_vec_1_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"xtile_V_vec_1_read\" :  \"" << xtile_V_vec_1_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ypartial_address0\" :  \"" << ypartial_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ypartial_ce0\" :  \"" << ypartial_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ypartial_we0\" :  \"" << ypartial_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ypartial_d0\" :  \"" << ypartial_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ypartial_q0\" :  \"" << ypartial_q0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"i1\" :  \"" << i1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"i2\" :  \"" << i2.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

