// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Loop_memset_y_proc_HH_
#define _Loop_memset_y_proc_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Loop_memset_y_proc : public sc_module {
    // Port declarations 18
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<1> > y_address0;
    sc_out< sc_logic > y_ce0;
    sc_out< sc_logic > y_we0;
    sc_out< sc_lv<32> > y_d0;
    sc_in< sc_lv<32> > y_q0;
    sc_in< sc_lv<32> > A_dout;
    sc_in< sc_logic > A_empty_n;
    sc_out< sc_logic > A_read;
    sc_out< sc_lv<1> > x_address0;
    sc_out< sc_logic > x_ce0;
    sc_in< sc_lv<32> > x_q0;


    // Module declarations
    Loop_memset_y_proc(sc_module_name name);
    SC_HAS_PROCESS(Loop_memset_y_proc);

    ~Loop_memset_y_proc();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > A_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > icmp_ln27_fu_141_p2;
    sc_signal< sc_lv<1> > xor_ln25_fu_118_p2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<2> > i_fu_130_p2;
    sc_signal< sc_lv<2> > i_reg_177;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > y_addr_1_reg_182;
    sc_signal< sc_lv<1> > icmp_ln26_fu_124_p2;
    sc_signal< sc_lv<2> > j_fu_147_p2;
    sc_signal< sc_lv<2> > j_reg_190;
    sc_signal< bool > ap_block_state4;
    sc_signal< sc_lv<32> > A_read_reg_195;
    sc_signal< sc_lv<32> > mul_ln28_fu_158_p2;
    sc_signal< sc_lv<32> > mul_ln28_reg_205;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > ap_phi_mux_phi_ln25_i_phi_fu_84_p4;
    sc_signal< sc_lv<1> > phi_ln25_i_reg_80;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<2> > i4_0_i_reg_91;
    sc_signal< sc_lv<2> > j5_0_i_reg_102;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > zext_ln25_fu_113_p1;
    sc_signal< sc_lv<64> > zext_ln28_fu_136_p1;
    sc_signal< sc_lv<64> > zext_ln28_1_fu_153_p1;
    sc_signal< sc_lv<32> > add_ln28_fu_163_p2;
    sc_signal< sc_lv<32> > mul_ln28_fu_158_p1;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_A_blk_n();
    void thread_A_read();
    void thread_add_ln28_fu_163_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_block_state1();
    void thread_ap_block_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_phi_ln25_i_phi_fu_84_p4();
    void thread_ap_ready();
    void thread_i_fu_130_p2();
    void thread_icmp_ln26_fu_124_p2();
    void thread_icmp_ln27_fu_141_p2();
    void thread_j_fu_147_p2();
    void thread_mul_ln28_fu_158_p1();
    void thread_mul_ln28_fu_158_p2();
    void thread_x_address0();
    void thread_x_ce0();
    void thread_xor_ln25_fu_118_p2();
    void thread_y_address0();
    void thread_y_ce0();
    void thread_y_d0();
    void thread_y_we0();
    void thread_zext_ln25_fu_113_p1();
    void thread_zext_ln28_1_fu_153_p1();
    void thread_zext_ln28_fu_136_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
