#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("Atile_V_vec_0_dout", 32, hls_in, 0, "ap_fifo", "fifo_data", 1),
	Port_Property("Atile_V_vec_0_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 1),
	Port_Property("Atile_V_vec_0_read", 1, hls_out, 0, "ap_fifo", "fifo_update", 1),
	Port_Property("Atile_V_vec_1_dout", 32, hls_in, 1, "ap_fifo", "fifo_data", 1),
	Port_Property("Atile_V_vec_1_empty_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("Atile_V_vec_1_read", 1, hls_out, 1, "ap_fifo", "fifo_update", 1),
	Port_Property("xtile_V_vec_0_dout", 32, hls_in, 2, "ap_fifo", "fifo_data", 1),
	Port_Property("xtile_V_vec_0_empty_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 1),
	Port_Property("xtile_V_vec_0_read", 1, hls_out, 2, "ap_fifo", "fifo_update", 1),
	Port_Property("xtile_V_vec_1_dout", 32, hls_in, 3, "ap_fifo", "fifo_data", 1),
	Port_Property("xtile_V_vec_1_empty_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 1),
	Port_Property("xtile_V_vec_1_read", 1, hls_out, 3, "ap_fifo", "fifo_update", 1),
	Port_Property("ypartial_address0", 3, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("ypartial_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("ypartial_d0", 32, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("ypartial_q0", 32, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("ypartial_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("ypartial_address1", 3, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("ypartial_ce1", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("ypartial_d1", 32, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("ypartial_q1", 32, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("ypartial_we1", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("i1", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("i2", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "tiled_matvec";
